export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"
export const GET_ERROR = "GET_ERROR"
export const GET_ALL_BRAND = "GET_ALL_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"
export const GET_SUB_CATEGORY_ID = "GET_SUB_CATEGORY_ID"
export const CREATE_ProductS = "CREATE_ProductS"
export const GET_ALL_ProductS = "GET_ALL_ProductS"
export const GET_Product_DETAILS="GET_Product_DETAILS"
export const GET_ONE_CATEGORY="GET_ONE_CATEGORY"
export const GET_ONE_BRAND="GET_ONE_BRAND"
export const GET_Product_Like="GET_Product_Like"
export const DELETE_Product="DELETE_Product"
export const GET_ALL_PRODUCT_PAGE="GET_ALL_PRODUCT_PAGE"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"

